version: '3.8'

services:
  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server --requirepass 123456789
    volumes:
      - redis_data:/data

volumes:
  redis_data:
