server:
  port: 8080

spring:
  application:
    name: graduation_project
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/database_analysis
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    check-template-location: false
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
